<div>
	<div class="pbody" data-title="{lang push_to_home_index}" data-style="home_1" data-width="820" data-css-class="publish">
 	{{#data}} 
	<ul class="nav nav-pills mb10">
	  <li id="link_home_1" class="active">
	    <a href="javascript:void(0);" data-action="switchPushStyle" data-params="home_1">{lang style_1}</a>
	  </li>
	  <li id="link_home_2"><a href="javascript:void(0);" data-action="switchPushStyle" data-params="home_2">{lang style_2}</a></li>
	  <li id="link_home_3"><a href="javascript:void(0);" data-action="switchPushStyle" data-params="home_3">{lang style_3}</a></li>
	</ul>
	<div class="home-category clearfix mb10 ml10 mr10">
    <div class="span10 ml0 gallery" id="push_home_1">
    	<div class="gallery-198-300 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="1,198:300">{{#s1.image_path}}<img src="<?php echo base_url_r()?>{{s1.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s1.image_path}}{{^s1.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 120px;">{{/s1.image_path}}</a></div>
		<div class="gallery-143-149 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="2,143:149">{{#s2.image_path}}<img src="<?php echo base_url_r()?>{{s2.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s2.image_path}}{{^s2.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s2.image_path}}</a></div>
    	<div class="gallery-143-149 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="3,143:149">{{#s3.image_path}}<img src="<?php echo base_url_r()?>{{s3.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s3.image_path}}{{^s3.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s3.image_path}}</a></div>
    	<div class="gallery-288-149 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="4,288:149">{{#s4.image_path}}<img src="<?php echo base_url_r()?>{{s4.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s4.image_path}}{{^s4.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s4.image_path}}</a></div>
    	<div class="gallery-288-149 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="5,288:149">{{#s5.image_path}}<img src="<?php echo base_url_r()?>{{s5.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s5.image_path}}{{^s5.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s5.image_path}}</a></div>
    	<div class="gallery-143-149 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="6,143:149">{{#s6.image_path}}<img src="<?php echo base_url_r()?>{{s6.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s6.image_path}}{{^s6.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s6.image_path}}</a></div>
    	<div class="gallery-143-149 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="7,143:149">{{#s7.image_path}}<img src="<?php echo base_url_r()?>{{s7.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s7.image_path}}{{^s7.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s7.image_path}}</a></div>
	</div>
    <div class="span10 ml0 gallery hide" id="push_home_2">
    	<div class="gallery-193-300 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="1,193:300">{{#s1.image_path}}<img src="<?php echo base_url_r()?>{{s1.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s1.image_path}}{{^s1.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 120px;">{{/s1.image_path}}</a></div>
		<div class="gallery-193-300 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="2,193:300">{{#s2.image_path}}<img src="<?php echo base_url_r()?>{{s2.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s2.image_path}}{{^s2.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 120px;">{{/s2.image_path}}</a></div>
    	<div class="gallery-193-300 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="3,193:300">{{#s3.image_path}}<img src="<?php echo base_url_r()?>{{s3.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s3.image_path}}{{^s3.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 120px;">{{/s3.image_path}}</a></div>
    	<div class="gallery-193-300 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="4,193:300">{{#s4.image_path}}<img src="<?php echo base_url_r()?>{{s4.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s4.image_path}}{{^s4.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 120px;">{{/s4.image_path}}</a></div>
	</div>
    <div class="span10 ml0 gallery hide" id="push_home_3">
    	<div class="gallery-198-300 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="1,198:300">{{#s1.image_path}}<img src="<?php echo base_url_r()?>{{s1.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s1.image_path}}{{^s1.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 120px;">{{/s1.image_path}}</a></div>
		<div class="gallery-198-300 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="2,198:300">{{#s2.image_path}}<img src="<?php echo base_url_r()?>{{s2.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s2.image_path}}{{^s2.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 120px;">{{/s2.image_path}}</a></div>
    	<div class="gallery-188-149 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="3,188:149">{{#s3.image_path}}<img src="<?php echo base_url_r()?>{{s3.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s3.image_path}}{{^s3.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s3.image_path}}</a></div>
    	<div class="gallery-188-149 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="4,188:149">{{#s4.image_path}}<img src="<?php echo base_url_r()?>{{s4.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s4.image_path}}{{^s4.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s4.image_path}}</a></div>
    	<div class="gallery-188-149 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="5,188:149">{{#s5.image_path}}<img src="<?php echo base_url_r()?>{{s5.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s5.image_path}}{{^s5.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s5.image_path}}</a></div>
    	<div class="gallery-188-149 puzzing text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="6,188:149">{{#s6.image_path}}<img src="<?php echo base_url_r()?>{{s6.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s6.image_path}}{{^s6.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s6.image_path}}</a></div>
	</div>
	</div>
 	{{/data}} 
	</div>
</div>