# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Gold Daily

# Model Form Field configuration
form: $/dlnlab/aloexrates/models/golddaily/fields.yaml

# Model Class name
modelClass: DLNLab\AloExrates\Models\GoldDaily

# Default redirect location
defaultRedirect: dlnlab/aloexrates/golddaily

# Create page
create:
    title: Create Gold Daily
    redirect: dlnlab/aloexrates/golddaily/update/:id
    redirectClose: dlnlab/aloexrates/golddaily

# Update page
update:
    title: Edit Gold Daily
    redirect: dlnlab/aloexrates/golddaily
    redirectClose: dlnlab/aloexrates/golddaily

# Preview page
preview:
    title: Preview Gold Daily