# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Currency Daily

# Model Form Field configuration
form: $/dlnlab/aloexrates/models/currencydaily/fields.yaml

# Model Class name
modelClass: DLNLab\AloExrates\Models\CurrencyDaily

# Default redirect location
defaultRedirect: dlnlab/aloexrates/currencydaily

# Create page
create:
    title: Create Currency Daily
    redirect: dlnlab/aloexrates/currencydaily/update/:id
    redirectClose: dlnlab/aloexrates/currencydaily

# Update page
update:
    title: Edit Currency Daily
    redirect: dlnlab/aloexrates/currencydaily
    redirectClose: dlnlab/aloexrates/currencydaily

# Preview page
preview:
    title: Preview Currency Daily