# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/dlnlab/features/models/report/columns.yaml

# Model Class name
modelClass: DLNLab\Features\Models\Report

# List Title
title: Manage Reports

# Link URL for each record
recordUrl: dlnlab/features/reports/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Display checkboxes next to each record
showCheckboxes: true

# Default sorting column
# defaultSort:
#     column: created_at
#     direction: desc

# Display checkboxes next to each record
# showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt

# Filter widget configuration
filter: config_filter.yaml