# ===================================
# Filter Scope Definitions
# ===================================
scopes:

    #category:

        # Filter name
        #label: rainlab.blog::lang.posts.category

        # Model Class name
        #modelClass: RainLab\Blog\Models\Category

        # Model attribute to display for the name
        #nameFrom: name

        # Apply query scope
        #scope: FilterCategories

    pending:

        # Filter name
        label: Pending

        # Filter type
        type: checkbox

        # SQL Conditions
        conditions: status = 0
