# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: FbFeed

# Model Form Field configuration
form: $/dlnlab/fbnews/models/fbfeed/fields.yaml

# Model Class name
modelClass: DLNLab\FBNews\Models\FbFeed

# Default redirect location
defaultRedirect: dlnlab/fbnews/fbfeed

# Create page
create:
    title: Create FbFeed
    redirect: dlnlab/fbnews/fbfeed/update/:id
    redirectClose: dlnlab/fbnews/fbfeed

# Update page
update:
    title: Edit FbFeed
    redirect: dlnlab/fbnews/fbfeed
    redirectClose: dlnlab/fbnews/fbfeed

# Preview page
preview:
    title: Preview FbFeed