# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: AdsCategory

# Model Form Field configuration
form: $/dlnlab/classified/models/adscategory/fields.yaml

# Model Class name
modelClass: DLNLab\Classified\Models\AdsCategory

# Default redirect location
defaultRedirect: dlnlab/classified/adscategories

# Create page
create:
    title: Create AdsCategories
    redirect: dlnlab/classified/adscategories/update/:id
    redirectClose: dlnlab/classified/adscategories

# Update page
update:
    title: Edit AdsCategories
    redirect: dlnlab/classified/adscategories
    redirectClose: dlnlab/classified/adscategories

# Preview page
preview:
    title: Preview AdsCategories