	  <a id="BackToTop" href="javascript:;">{lang back_to_top}</a>
	  
	  <!--{subtemplate common/resources_footer}-->
	  
      <!--{subtemplate js_tpl/static_include_tpl}-->
			<script type="text/template" 
				id="data-actions"  
				data-login-url="<?php echo spUrl('webuser','login'); ?>" 
				data-bbslogin-url="<?php echo spUrl('webuser','bbs_login'); ?>" 
				data-loginredirect-url="<?php echo spUrl('my','shares');?>"
				data-mybasicsettings-url="<?php echo spUrl('my','setting_basic');?>"
				data-editshare-url="<?php echo spUrl('share','edit_share');?>"
				data-regredirect-url="<?php echo spUrl('pin','index');?>"
				data-register-url="<?php echo spUrl('webuser','ajax_register'); ?>" 
				data-ajaxgetshare-url="<?php echo spUrl('share','ajax_get_share'); ?>" 
				data-forwarding-url="<?php echo spUrl('share','forwarding'); ?>" 
				data-likeshare-url="<?php echo spUrl('share','add_like'); ?>" 
				data-likealbum-url="<?php echo spUrl('album','add_like'); ?>" 
				data-liketopic-url="<?php echo spUrl('topic','add_like'); ?>" 
				data-removelikealbum-url="<?php echo spUrl('album','remove_like'); ?>" 
				data-addcomment-url="<?php echo spUrl('share','add_comment'); ?>" 
				data-delcomment-url="<?php echo spUrl('share','del_comment'); ?>"
				data-delshare-url="<?php echo spUrl('share','delete_share'); ?>"
				data-avatarupload-url="<?php echo spUrl('webuser','upload_avatar');?>" 
				data-avatarsave-url="<?php echo spUrl('webuser','save_avatar');?>"
				data-ajax-nickname="<?php echo spUrl('webuser','ajax_nick_check');?>"
				data-ajax-updatenickname="<?php echo spUrl('webuser','nickname_update_check');?>"
				data-ajax-albumcreate="<?php echo spUrl('album','album_create');?>"
				data-ajax-resetpasswd="<?php echo spUrl('webuser','reset_passwd');?>"
				data-ajax-message="<?php echo spUrl('ajaxmessage','fetch');?>"
				data-updateuser-url="<?php echo spUrl('webuser','update_userinfo');?>"
				data-ajax-email="<?php echo spUrl('webuser','ajax_email_check');?>"
				data-categorylist-url="<?php echo spUrl('album','category_list');?>"
				data-smiles-url="<?php echo spUrl('misc','smiles');?>"
				data-addfollow-url="<?php echo spUrl('relation','add_follow');?>"
				data-removefollow-url="<?php echo spUrl('relation','remove_follow');?>"
				data-applystar-url="<?php echo spUrl('staruser','apply');?>"
				data-applyshop-url="<?php echo spUrl('goodshop','apply');?>"
				data-albumlist-url="<?php echo spUrl('album','album_list');?>"
				data-taglist-url="<?php echo spUrl('album','tag_list');?>"
				data-tags-url="<?php echo spUrl('album','tags');?>"
				data-fetchtpl-url="<?php echo spUrl('ajaxtpl','render_tpl');?>"
				data-editalbum-url="<?php echo spUrl('album','album_edit');?>"
				data-delalbum-url="<?php echo spUrl('album','album_delete');?>"
				data-myalbum-url="<?php echo spUrl('my','album');?>"
				data-userprofile-url="<?php echo spUrl('webuser','user_profile');?>"
				data-editgoodshop-url="<?php echo spUrl('my','update_shop');?>"
				data-forum-setting-url="<?php echo spUrl('webuser','bind_forum');?>"
				data-vcode-url="<?php echo spUrl('misc','vcode');?>"
				data-vcheck-url="<?php echo spUrl('misc','ajax_vcheck');?>"
				data-create_topic-url="<?php echo spUrl('my','create_topic');?>"
				data-update_topic-url="<?php echo spUrl('my','update_topic');?>"
				data-tbannersave-url="<?php echo spUrl('my','save_tbanner');?>"
				data-gbannersave-url="<?php echo spUrl('my','save_gbanner');?>"
				data-create_group-url="<?php echo spUrl('my','create_group');?>"
				data-update_group-url="<?php echo spUrl('my','update_group');?>"
				data-upload-save-url="<?php echo spUrl('share','item_upload', array('act'=>'save'));?>"
				data-fetch-save-url="<?php echo spUrl('share','item_fetch', array('act'=>'save'));?>"
				data-edit-save-url="<?php echo spUrl('admin','item_list', array('act'=>'edit_save'));?>"
				data-upload-url="<?php echo spUrl('share','item_upload', array('act'=>'upload'));?>" 
				data-fetch-url="<?php echo spUrl('share','item_fetch', array('act'=>'fetch'));?>"
				data-video-save-url="<?php echo spUrl('share','video_fetch', array('act'=>'save'));?>"
				data-video-fetch-url="<?php echo spUrl('share','video_fetch', array('act'=>'fetch'));?>"
				data-article-save-url="<?php echo spUrl('share','article', array('act'=>'save'));?>"
				data-joinGroup-url="<?php echo spUrl('group','join_group');?>"
				data-substorecat-url="<?php echo spUrl('goodshop','subCategory');?>"
				data-createalbum-url="<?php echo spUrl('my','album_create');?>"
				data-updatealbum-url="<?php echo spUrl('my','album_update');?>"
				data-fetchhotshare-url="<?php echo spUrl('share','find_category_hot_share');?>"
				data-crophotshare-url="<?php echo spUrl('share','crop_category_hot_share');?>"
				data-getstar-url="<?php echo spUrl('staruser','get_staruser');?>"
				data-savestar-url="<?php echo spUrl('staruser','save_staruser'); ?>"
				data-starcovercrop-url="<?php echo spUrl('staruser','crop_staruser_cover');?>"
				data-sendmessage-url="<?php echo spUrl('my','sendmessage'); ?>"
				data-forgetpassword-url="<?php echo spUrl('webuser','forget_password');?>"
				data-domaincheck-url="<?php echo spUrl('webuser','ajax_domain_valid');?>"
				>
			</script>
			<script type="text/template" 
				id="data-tips"  
				data-welcome="{lang welcome_to_pintuxiu}" 
				data-error="{lang error}" 
				data-no-selection="{lang no_selection}"
				data-confirm-delete-share="{lang confirm_delete_share}"
				data-confirm-delete-comment="{lang confirm_delete_comment}"
				data-confirm-delete-album="{lang confirm_delete_album}"
				data-confirm-banuser="{lang confirm_delete_banuser}"
				data-not-null="{lang not_null}"
				data-required-field="{lang required_field}"
				data-not_valid="{lang not_valid}"
				data-intro_length_not_valid="{lang intro_length_not_valid}"
				data-title_length_not_valid="{lang title_length_not_valid}"
				data-img_desc_not_valid="{lang img_desc_not_valid}"
				data-no_img_cover_selected="{lang no_img_cover_selected}"
				data-no_img_share="{lang no_img_share}"
				data-album_cannot_be_null="{lang album_cannot_be_null}"
				data-gooshop_desc_not_valid="{lang gooshop_desc_not_valid}"
				data-nick_not_valid="{lang nick_not_valid}"
				data-nick_already_existed="{lang nick_already_existed}"
				data-email_already_existed="{lang email_already_existed}"
				data-password_not_valid="{lang password_not_valid}"
				data-password_not_match="{lang password_not_match}"
				data-not_all_digit="{lang not_all_digit}"
				data-length_rang="{lang length_rang}"
				data-link-not-null="{lang link_not_null}"
				data-success="{lang operate_succeed}" 
				data-loading="{lang loading}" 
				data-load_complete="{lang load_complete}" 
				data-fetch-success="{lang fetch_succeed}"
				data-fetch-faild="{lang fetch_failed}"
				data-no-image-fetch="{lang no_img_fetch}"
				data-loading-detail="{lang loading-detail}" 
				data-server-error="{lang server-error}" 
				data-add-like="{lang add_like_plus}" 
				data-remove-like="{lang remove_add_like}" 
				data-not_liked="{lang not_liked}" 
				data-like-already="{lang add_like_already}" 
				data-no-permission="{lang no_permission}" 
				data-forward-self="{lang forward_self}" 
				data-like-self="{lang like_self}"
				data-type_some="{lang type_some}"
				data-done="{lang done}"
				data-select_file="{lang select_file}"
				data-uploading="{lang uploading}"
				data-pls_select="{lang pls_select}"
				data-vcode_wrong="{lang vcode_wrong}"
				>
		</script>
		
   </body>
</html>