# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Bank Daily

# Model Form Field configuration
form: $/dlnlab/aloexrates/models/bankdaily/fields.yaml

# Model Class name
modelClass: DLNLab\AloExrates\Models\BankDaily

# Default redirect location
defaultRedirect: dlnlab/aloexrates/bankdaily

# Create page
create:
    title: Create Bank Daily
    redirect: dlnlab/aloexrates/bankdaily/update/:id
    redirectClose: dlnlab/aloexrates/bankdaily

# Update page
update:
    title: Edit Bank Daily
    redirect: dlnlab/aloexrates/bankdaily
    redirectClose: dlnlab/aloexrates/bankdaily

# Preview page
preview:
    title: Preview Bank Daily